apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: multi-module-example

- description: Country Service data directory
  name: DATA_DIRECTORY
  value: /deployments/data
  required: true

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: country-service
      delete: blog
    name: country-service
  spec:
    replicas: 1
    selector:
      deploymentconfig: country-service
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: country-service
          delete: blog
          deploymentconfig: country-service
      spec:
        containers:
        - env:
          - name: DATA_DIRECTORY
            value: ${DATA_DIRECTORY}
          image: country-service
          imagePullPolicy: Always
          name: country-service
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 8080
            name: http
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 384Mi
            requests:
              cpu: 250m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        automatic: false
        containerNames:
        - country-service
        from:
          kind: ImageStreamTag
          name: country-service:test
          namespace: dev
      type: ImageChange
    - type: ConfigChange
  status: {}
  
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: country-web
      delete: blog
    name: country-web
  spec:
    replicas: 1
    selector:
      deploymentconfig: country-web
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: country-web
          delete: blog
          deploymentconfig: country-web
      spec:
        containers:
        - image: country-web:latest
          imagePullPolicy: Always
          name: country-web
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        automatic: false
        containerNames:
        - country-web
        from:
          kind: ImageStreamTag
          name: country-web:latest
          namespace: dev
      type: ImageChange
    - type: ConfigChange
  status: {}
  
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: country-service
      delete: blog
    name: country-service
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: dev/country-service:test
      generation: null
      importPolicy: {}
      name: latest
  status: {}
    
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: country-web
      delete: blog
    name: country-web
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: dev/country-web:test
      generation: null
      importPolicy: {}
      name: latest
  status: {}
    
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: country-service
      delete: blog
    name: country-service
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      deploymentconfig: country-service
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
    
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: country-web
      delete: blog
    name: country-web
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      deploymentconfig: country-web
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
    
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      app: country-service
      delete: blog
    name: country-service
  spec:
    to:
      kind: Service
      name: country-service
    port:
      targetPort: 8080-tcp
  status: {}
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      app: country-web
      delete: blog
    name: country-web
  spec:
    to:
      kind: Service
      name: country-web
    port:
      targetPort: 8080-tcp
  status: {}
